# DataSource Config
spring:
  datasource:
    driver-class-name : com.p6spy.engine.spy.P6SpyDriver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://rm-uf6297v9jn0kv20s72o.mysql.rds.aliyuncs.com:3306/washcar_db
    username: cw_admin
    password: 8uHto4CHA@FL



# Logger Config
logging:
  level:
    com.p6spy: info
  file:
    name: D:/mogo/wash/wash.log

# MyBatis-Plus 配置
